.TH docs/psv-vpk.1.md 1 PSVSDK
.SH NAME

psv-vpk - Generate a Vita PacKage

.SH SYNOPSIS

    psv-vpk [HOST_PATH[:VPK_PATH]]... > out.vpk

.SH OPTIONS

  - HOST_PATH: path on the host filesystem (file or folder)
  - VPK_PATH:  path inside the package (HOST_PATH if no given)

.SH EXAMPLES

    psv-vpk app.sfo:sce_sys/param.sfo app.self:eboot.bin

.SH NOTES

Generated archive won't have CRCs (unused by the installer)
This can be seen as an issue from regular archive manager.
You can still extract them using: `unzip -od. no-crc.vpk`

.SH SEE ALSO
  - vpk(5)
