.TH docs/psv-vpk.1.md 1 PSVSDK
.SH NAME
  psv-vpk - Generate a Vita PacKage

.SH SYNOPSIS
	psv-vpk [HOST_PATH[:VPK_PATH]]... [<in.self] >out.vpk

.SH OPTIONS
 - HOST_PATH: path on the host filesystem (file or folder)
 - VPK_PATH:  path inside the package (HOST_PATH if no given)

.SH EXAMPLES

	psv-vpk < a.self
	psv-vpk sce_sys assets:data a.self:eboot.bin
	psv-vpk <(psv-sfo TITLE="Hello World" ...):sce_sys/param.sfo < a.self

.SH NOTES

  Archived files will have they CRC field unset (because unchecked during unpacking)
  To extract VPK simply unzip it using: `unzip -od. *.vpk` (ignore bad CRC warning)

.SH SEE ALSO
  - vpk(5)
