.TH docs/psv-velf.1.md 1 PSVSDK
.SH NAME

psv-velf - Generate a Vita ELF

.SH SYNOPSIS

    psv-velf in.elf out.velf

.SH ENVIRONMENT VARIABLES
  - DEBUG (any value): print more details on stderr

.SH NOTES

A better configuration system shall used
to specify module name,nid,version ...

.SH SEE ALSO
  - velf(5)
